version: '3'
services:
  inquisitor:
    build:
      context: .
      dockerfile: Dockerfile
    command: python /app/inquisitor.py 192.168.206.67 a4:83:e7:99:92:0a 192.168.206.67 A4:83:E7:99:92:0A
    volumes:
      - ./inquisitor.py:/app/inquisitor.py