build:
	sudo docker build -t inquisitor .


run:
	docker run inquisitor python /app/inquisitor.py 192.168.206.67 a4:83:e7:99:92:0a 192.168.206.67 A4:83:E7:99:92:0A



run_v:
	docker run -v /Users/chajjar/Documents/Inquisitor:/app inquisitor python3 /app/inquisitor.py 192.168.206.67 a4:83:e7:99:92:0a 192.168.206.67 A4:83:E7:99:92:0A --verbose