build:
	sudo docker build -t inquisitor .


run:
	docker run inquisitor python /app/inquisitor.py 



run_v:
	docker run -v /Users/chajjar/Documents/Inquisitor:/app inquisitor python3 /app/inquisitor.py  --verbose
